### ISSUE TITLE
App crashes on reload with No implementation found for clearStateNativeJsi()

### ISSUE THREAD

**Issue by ShivamJoker** [margelo/react-native-nitro-sqlite#23]
My package versions are following:
```json
    "react-native": "0.72.5",
    "react-native-quick-sqlite": "^8.0.5",
```
Everything works fine except reloads.

This is the complete error:

```sh
FATAL EXCEPTION: mqt_native_modules
Process: com.sqlplay, PID: 26910
java.lang.UnsatisfiedLinkError: No implementation found for void com.reactnativequicksqlite.QuickSQLiteBridge.clearStateNativeJsi() (tried Java_com_reactnativequicksqlite_QuickSQLiteBridge_clearStateNativeJsi and Java_com_reactnativequicksqlite_QuickSQLiteBridge_clearStateNativeJsi__)
	at com.reactnativequicksqlite.QuickSQLiteBridge.clearStateNativeJsi(Native Method)
	at com.reactnativequicksqlite.QuickSQLiteBridge.clearState(QuickSQLiteBridge.java:27)
	at com.reactnativequicksqlite.SequelModule.onCatalystInstanceDestroy(SequelModule.java:41)
	at com.facebook.react.bridge.BaseJavaModule.invalidate(BaseJavaModule.java:76)
	at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:110)
	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:108)
	at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:359)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:254)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:923
```

**Comment by 1987cr** [comment]
Having the same error.

**Comment by ShivamJoker** [comment]
@mrousavy any ideas how this can be fixed?

**Comment by rezkiy37** [comment]
We have a problem when we are building an Android app with a flag - [--active-arch-only](https://reactnative.dev/docs/build-speed#build-only-one-abi-during-development-android-only).

<img width="1293" alt="Error" src="https://github.com/margelo/react-native-quick-sqlite/assets/57314631/7729e129-28a5-4c11-9769-ab2d979f8580">

**Comment by mrousavy** [comment]
> @mrousavy any ideas how this can be fixed?

@ShivamJoker not right now, I would need to investigate this.

**Comment by mrousavy** [comment]
Fixed with #24

**Comment by ShivamJoker** [comment]
Thanks.

**Comment by riteshreg** [comment]
having same issue
